# Generated by Django 3.2.2 on 2021-09-05 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 5, 27, 792488, tzinfo=utc)),
        ),
    ]
