# Generated by Django 3.2.2 on 2021-08-24 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_worst', models.IntegerField()),
                ('area_mean', models.IntegerField()),
                ('area_standard_error', models.IntegerField()),
                ('perimeter_worst', models.IntegerField()),
                ('perimeter_mean', models.IntegerField()),
                ('radius_worst', models.IntegerField()),
                ('radius_mean', models.IntegerField()),
                ('perimeter_standard_error', models.IntegerField()),
                ('texture_worst', models.IntegerField()),
                ('texture_mean', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField()),
                ('glucose_level', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('skinthickness', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('DiabetesPedigreeFunction', models.IntegerField()),
                ('age', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Heart_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('chest_pain_type', models.CharField(max_length=100)),
                ('resting_blood_pressure', models.IntegerField()),
                ('cholestrol', models.IntegerField()),
                ('fasting_blood_sugar', models.IntegerField()),
                ('resting_ecg', models.CharField(max_length=100)),
                ('heart_rate', models.IntegerField()),
                ('excersise_induced_angina', models.CharField(max_length=100)),
                ('st_depression', models.IntegerField()),
                ('st_segment', models.CharField(max_length=100)),
                ('major_vessels', models.CharField(max_length=100)),
                ('thal', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kidney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('wbc_count', models.IntegerField()),
                ('blood_urea', models.IntegerField()),
                ('appetite', models.CharField(max_length=100)),
                ('blood_glucose_random', models.IntegerField()),
                ('pus_cell_clumps', models.CharField(max_length=100)),
                ('hypertension', models.CharField(max_length=100)),
                ('anemia', models.CharField(max_length=100)),
                ('packed_cell_volume', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Liver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('bilirubin', models.IntegerField()),
                ('direct_bilirubin', models.IntegerField()),
                ('alkaline_phosphotase', models.IntegerField()),
                ('alamine_aminotransferase', models.IntegerField()),
                ('aspartate_aminotransferase', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('albumin', models.IntegerField()),
                ('albumin_and_globulin_ratio', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
