# Generated by Django 3.2.2 on 2021-09-05 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_auto_20210905_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 3, 49, 539657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='covid',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 3, 49, 539657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 3, 49, 536658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='heart_disease',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 3, 49, 534656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kidney',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 3, 49, 538657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='liver',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 5, 8, 3, 49, 537655, tzinfo=utc)),
        ),
    ]
